/**
 * Bulk seed ISO 3166-1 alpha-2 country codes (+ our Unknown "??").
 * All scores default to 0. Re-runnable (upsert semantics).
 */

const countries = [
  { country_code2: '??', name: 'Unknown', country_code3: null, score: 0 },
  { country_code2: 'AF', name: 'Afghanistan', country_code3: 'AFG', score: 0 },
  { country_code2: 'AL', name: 'Albania', country_code3: 'ALB', score: 0 },
  { country_code2: 'DZ', name: 'Algeria', country_code3: 'DZA', score: 0 },
  { country_code2: 'AS', name: 'American Samoa', country_code3: 'ASM', score: 0 },
  { country_code2: 'AD', name: 'Andorra', country_code3: 'AND', score: 0 },
  { country_code2: 'AO', name: 'Angola', country_code3: 'AGO', score: 0 },
  { country_code2: 'AI', name: 'Anguilla', country_code3: 'AIA', score: 0 },
  { country_code2: 'AQ', name: 'Antarctica', country_code3: 'ATA', score: 0 },
  { country_code2: 'AG', name: 'Antigua and Barbuda', country_code3: 'ATG', score: 0 },
  { country_code2: 'AR', name: 'Argentina', country_code3: 'ARG', score: 0 },
  { country_code2: 'AM', name: 'Armenia', country_code3: 'ARM', score: 0 },
  { country_code2: 'AW', name: 'Aruba', country_code3: 'ABW', score: 0 },
  { country_code2: 'AU', name: 'Australia', country_code3: 'AUS', score: 0 },
  { country_code2: 'AT', name: 'Austria', country_code3: 'AUT', score: 0 },
  { country_code2: 'AZ', name: 'Azerbaijan', country_code3: 'AZE', score: 0 },
  { country_code2: 'BS', name: 'Bahamas', country_code3: 'BHS', score: 0 },
  { country_code2: 'BH', name: 'Bahrain', country_code3: 'BHR', score: 0 },
  { country_code2: 'BD', name: 'Bangladesh', country_code3: 'BGD', score: 0 },
  { country_code2: 'BB', name: 'Barbados', country_code3: 'BRB', score: 0 },
  { country_code2: 'BY', name: 'Belarus', country_code3: 'BLR', score: 0 },
  { country_code2: 'BE', name: 'Belgium', country_code3: 'BEL', score: 0 },
  { country_code2: 'BZ', name: 'Belize', country_code3: 'BLZ', score: 0 },
  { country_code2: 'BJ', name: 'Benin', country_code3: 'BEN', score: 0 },
  { country_code2: 'BM', name: 'Bermuda', country_code3: 'BMU', score: 0 },
  { country_code2: 'BT', name: 'Bhutan', country_code3: 'BTN', score: 0 },
  { country_code2: 'BO', name: 'Bolivia', country_code3: 'BOL', score: 0 },
  { country_code2: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', country_code3: 'BES', score: 0 },
  { country_code2: 'BA', name: 'Bosnia and Herzegovina', country_code3: 'BIH', score: 0 },
  { country_code2: 'BW', name: 'Botswana', country_code3: 'BWA', score: 0 },
  { country_code2: 'BV', name: 'Bouvet Island', country_code3: 'BVT', score: 0 },
  { country_code2: 'BR', name: 'Brazil', country_code3: 'BRA', score: 0 },
  { country_code2: 'IO', name: 'British Indian Ocean Territory', country_code3: 'IOT', score: 0 },
  { country_code2: 'BN', name: 'Brunei Darussalam', country_code3: 'BRN', score: 0 },
  { country_code2: 'BG', name: 'Bulgaria', country_code3: 'BGR', score: 0 },
  { country_code2: 'BF', name: 'Burkina Faso', country_code3: 'BFA', score: 0 },
  { country_code2: 'BI', name: 'Burundi', country_code3: 'BDI', score: 0 },
  { country_code2: 'CV', name: 'Cabo Verde', country_code3: 'CPV', score: 0 },
  { country_code2: 'KH', name: 'Cambodia', country_code3: 'KHM', score: 0 },
  { country_code2: 'CM', name: 'Cameroon', country_code3: 'CMR', score: 0 },
  { country_code2: 'CA', name: 'Canada', country_code3: 'CAN', score: 0 },
  { country_code2: 'KY', name: 'Cayman Islands', country_code3: 'CYM', score: 0 },
  { country_code2: 'CF', name: 'Central African Republic', country_code3: 'CAF', score: 0 },
  { country_code2: 'TD', name: 'Chad', country_code3: 'TCD', score: 0 },
  { country_code2: 'CL', name: 'Chile', country_code3: 'CHL', score: 0 },
  { country_code2: 'CN', name: 'China', country_code3: 'CHN', score: 0 },
  { country_code2: 'CX', name: 'Christmas Island', country_code3: 'CXR', score: 0 },
  { country_code2: 'CC', name: 'Cocos (Keeling) Islands', country_code3: 'CCK', score: 0 },
  { country_code2: 'CO', name: 'Colombia', country_code3: 'COL', score: 0 },
  { country_code2: 'KM', name: 'Comoros', country_code3: 'COM', score: 0 },
  { country_code2: 'CG', name: 'Congo', country_code3: 'COG', score: 0 },
  {
    country_code2: 'CD',
    name: 'Congo, Democratic Republic of the',
    country_code3: 'COD',
    score: 0
  },
  { country_code2: 'CK', name: 'Cook Islands', country_code3: 'COK', score: 0 },
  { country_code2: 'CR', name: 'Costa Rica', country_code3: 'CRI', score: 0 },
  { country_code2: 'CI', name: "Côte d'Ivoire", country_code3: 'CIV', score: 0 },
  { country_code2: 'HR', name: 'Croatia', country_code3: 'HRV', score: 0 },
  { country_code2: 'CU', name: 'Cuba', country_code3: 'CUB', score: 0 },
  { country_code2: 'CW', name: 'Curaçao', country_code3: 'CUW', score: 0 },
  { country_code2: 'CY', name: 'Cyprus', country_code3: 'CYP', score: 0 },
  { country_code2: 'CZ', name: 'Czechia', country_code3: 'CZE', score: 0 },
  { country_code2: 'DK', name: 'Denmark', country_code3: 'DNK', score: 0 },
  { country_code2: 'DJ', name: 'Djibouti', country_code3: 'DJI', score: 0 },
  { country_code2: 'DM', name: 'Dominica', country_code3: 'DMA', score: 0 },
  { country_code2: 'DO', name: 'Dominican Republic', country_code3: 'DOM', score: 0 },
  { country_code2: 'EC', name: 'Ecuador', country_code3: 'ECU', score: 0 },
  { country_code2: 'EG', name: 'Egypt', country_code3: 'EGY', score: 0 },
  { country_code2: 'SV', name: 'El Salvador', country_code3: 'SLV', score: 0 },
  { country_code2: 'GQ', name: 'Equatorial Guinea', country_code3: 'GNQ', score: 0 },
  { country_code2: 'ER', name: 'Eritrea', country_code3: 'ERI', score: 0 },
  { country_code2: 'EE', name: 'Estonia', country_code3: 'EST', score: 0 },
  { country_code2: 'SZ', name: 'Eswatini', country_code3: 'SWZ', score: 0 },
  { country_code2: 'ET', name: 'Ethiopia', country_code3: 'ETH', score: 0 },
  { country_code2: 'FK', name: 'Falkland Islands (Malvinas)', country_code3: 'FLK', score: 0 },
  { country_code2: 'FO', name: 'Faroe Islands', country_code3: 'FRO', score: 0 },
  { country_code2: 'FJ', name: 'Fiji', country_code3: 'FJI', score: 0 },
  { country_code2: 'FI', name: 'Finland', country_code3: 'FIN', score: 0 },
  { country_code2: 'FR', name: 'France', country_code3: 'FRA', score: 0 },
  { country_code2: 'GF', name: 'French Guiana', country_code3: 'GUF', score: 0 },
  { country_code2: 'PF', name: 'French Polynesia', country_code3: 'PYF', score: 0 },
  { country_code2: 'TF', name: 'French Southern Territories', country_code3: 'ATF', score: 0 },
  { country_code2: 'GA', name: 'Gabon', country_code3: 'GAB', score: 0 },
  { country_code2: 'GM', name: 'Gambia', country_code3: 'GMB', score: 0 },
  { country_code2: 'GE', name: 'Georgia', country_code3: 'GEO', score: 0 },
  { country_code2: 'DE', name: 'Germany', country_code3: 'DEU', score: 0 },
  { country_code2: 'GH', name: 'Ghana', country_code3: 'GHA', score: 0 },
  { country_code2: 'GI', name: 'Gibraltar', country_code3: 'GIB', score: 0 },
  { country_code2: 'GR', name: 'Greece', country_code3: 'GRC', score: 0 },
  { country_code2: 'GL', name: 'Greenland', country_code3: 'GRL', score: 0 },
  { country_code2: 'GD', name: 'Grenada', country_code3: 'GRD', score: 0 },
  { country_code2: 'GP', name: 'Guadeloupe', country_code3: 'GLP', score: 0 },
  { country_code2: 'GU', name: 'Guam', country_code3: 'GUM', score: 0 },
  { country_code2: 'GT', name: 'Guatemala', country_code3: 'GTM', score: 0 },
  { country_code2: 'GG', name: 'Guernsey', country_code3: 'GGY', score: 0 },
  { country_code2: 'GN', name: 'Guinea', country_code3: 'GIN', score: 0 },
  { country_code2: 'GW', name: 'Guinea-Bissau', country_code3: 'GNB', score: 0 },
  { country_code2: 'GY', name: 'Guyana', country_code3: 'GUY', score: 0 },
  { country_code2: 'HT', name: 'Haiti', country_code3: 'HTI', score: 0 },
  {
    country_code2: 'HM',
    name: 'Heard Island and McDonald Islands',
    country_code3: 'HMD',
    score: 0
  },
  { country_code2: 'VA', name: 'Holy See', country_code3: 'VAT', score: 0 },
  { country_code2: 'HN', name: 'Honduras', country_code3: 'HND', score: 0 },
  { country_code2: 'HK', name: 'Hong Kong', country_code3: 'HKG', score: 0 },
  { country_code2: 'HU', name: 'Hungary', country_code3: 'HUN', score: 0 },
  { country_code2: 'IS', name: 'Iceland', country_code3: 'ISL', score: 0 },
  { country_code2: 'IN', name: 'India', country_code3: 'IND', score: 0 },
  { country_code2: 'ID', name: 'Indonesia', country_code3: 'IDN', score: 0 },
  { country_code2: 'IR', name: 'Iran, Islamic Republic of', country_code3: 'IRN', score: 0 },
  { country_code2: 'IQ', name: 'Iraq', country_code3: 'IRQ', score: 0 },
  { country_code2: 'IE', name: 'Ireland', country_code3: 'IRL', score: 0 },
  { country_code2: 'IM', name: 'Isle of Man', country_code3: 'IMN', score: 0 },
  { country_code2: 'IL', name: 'Israel', country_code3: 'ISR', score: 0 },
  { country_code2: 'IT', name: 'Italy', country_code3: 'ITA', score: 0 },
  { country_code2: 'JM', name: 'Jamaica', country_code3: 'JAM', score: 0 },
  { country_code2: 'JP', name: 'Japan', country_code3: 'JPN', score: 0 },
  { country_code2: 'JE', name: 'Jersey', country_code3: 'JEY', score: 0 },
  { country_code2: 'JO', name: 'Jordan', country_code3: 'JOR', score: 0 },
  { country_code2: 'KZ', name: 'Kazakhstan', country_code3: 'KAZ', score: 0 },
  { country_code2: 'KE', name: 'Kenya', country_code3: 'KEN', score: 0 },
  { country_code2: 'KI', name: 'Kiribati', country_code3: 'KIR', score: 0 },
  {
    country_code2: 'KP',
    name: "Korea, Democratic People's Republic of",
    country_code3: 'PRK',
    score: 0
  },
  { country_code2: 'KR', name: 'Korea, Republic of', country_code3: 'KOR', score: 0 },
  { country_code2: 'KW', name: 'Kuwait', country_code3: 'KWT', score: 0 },
  { country_code2: 'KG', name: 'Kyrgyzstan', country_code3: 'KGZ', score: 0 },
  { country_code2: 'LA', name: "Lao People's Democratic Republic", country_code3: 'LAO', score: 0 },
  { country_code2: 'LV', name: 'Latvia', country_code3: 'LVA', score: 0 },
  { country_code2: 'LB', name: 'Lebanon', country_code3: 'LBN', score: 0 },
  { country_code2: 'LS', name: 'Lesotho', country_code3: 'LSO', score: 0 },
  { country_code2: 'LR', name: 'Liberia', country_code3: 'LBR', score: 0 },
  { country_code2: 'LY', name: 'Libya', country_code3: 'LBY', score: 0 },
  { country_code2: 'LI', name: 'Liechtenstein', country_code3: 'LIE', score: 0 },
  { country_code2: 'LT', name: 'Lithuania', country_code3: 'LTU', score: 0 },
  { country_code2: 'LU', name: 'Luxembourg', country_code3: 'LUX', score: 0 },
  { country_code2: 'MO', name: 'Macao', country_code3: 'MAC', score: 0 },
  { country_code2: 'MG', name: 'Madagascar', country_code3: 'MDG', score: 0 },
  { country_code2: 'MW', name: 'Malawi', country_code3: 'MWI', score: 0 },
  { country_code2: 'MY', name: 'Malaysia', country_code3: 'MYS', score: 0 },
  { country_code2: 'MV', name: 'Maldives', country_code3: 'MDV', score: 0 },
  { country_code2: 'ML', name: 'Mali', country_code3: 'MLI', score: 0 },
  { country_code2: 'MT', name: 'Malta', country_code3: 'MLT', score: 0 },
  { country_code2: 'MH', name: 'Marshall Islands', country_code3: 'MHL', score: 0 },
  { country_code2: 'MQ', name: 'Martinique', country_code3: 'MTQ', score: 0 },
  { country_code2: 'MR', name: 'Mauritania', country_code3: 'MRT', score: 0 },
  { country_code2: 'MU', name: 'Mauritius', country_code3: 'MUS', score: 0 },
  { country_code2: 'YT', name: 'Mayotte', country_code3: 'MYT', score: 0 },
  { country_code2: 'MX', name: 'Mexico', country_code3: 'MEX', score: 0 },
  { country_code2: 'FM', name: 'Micronesia, Federated States of', country_code3: 'FSM', score: 0 },
  { country_code2: 'MD', name: 'Moldova, Republic of', country_code3: 'MDA', score: 0 },
  { country_code2: 'MC', name: 'Monaco', country_code3: 'MCO', score: 0 },
  { country_code2: 'MN', name: 'Mongolia', country_code3: 'MNG', score: 0 },
  { country_code2: 'ME', name: 'Montenegro', country_code3: 'MNE', score: 0 },
  { country_code2: 'MS', name: 'Montserrat', country_code3: 'MSR', score: 0 },
  { country_code2: 'MA', name: 'Morocco', country_code3: 'MAR', score: 0 },
  { country_code2: 'MZ', name: 'Mozambique', country_code3: 'MOZ', score: 0 },
  { country_code2: 'MM', name: 'Myanmar', country_code3: 'MMR', score: 0 },
  { country_code2: 'NA', name: 'Namibia', country_code3: 'NAM', score: 0 },
  { country_code2: 'NR', name: 'Nauru', country_code3: 'NRU', score: 0 },
  { country_code2: 'NP', name: 'Nepal', country_code3: 'NPL', score: 0 },
  { country_code2: 'NL', name: 'Netherlands', country_code3: 'NLD', score: 0 },
  { country_code2: 'NC', name: 'New Caledonia', country_code3: 'NCL', score: 0 },
  { country_code2: 'NZ', name: 'New Zealand', country_code3: 'NZL', score: 0 },
  { country_code2: 'NI', name: 'Nicaragua', country_code3: 'NIC', score: 0 },
  { country_code2: 'NE', name: 'Niger', country_code3: 'NER', score: 0 },
  { country_code2: 'NG', name: 'Nigeria', country_code3: 'NGA', score: 0 },
  { country_code2: 'NU', name: 'Niue', country_code3: 'NIU', score: 0 },
  { country_code2: 'NF', name: 'Norfolk Island', country_code3: 'NFK', score: 0 },
  { country_code2: 'MK', name: 'North Macedonia', country_code3: 'MKD', score: 0 },
  { country_code2: 'MP', name: 'Northern Mariana Islands', country_code3: 'MNP', score: 0 },
  { country_code2: 'NO', name: 'Norway', country_code3: 'NOR', score: 0 },
  { country_code2: 'OM', name: 'Oman', country_code3: 'OMN', score: 0 },
  { country_code2: 'PK', name: 'Pakistan', country_code3: 'PAK', score: 0 },
  { country_code2: 'PW', name: 'Palau', country_code3: 'PLW', score: 0 },
  { country_code2: 'PS', name: 'Palestine, State of', country_code3: 'PSE', score: 0 },
  { country_code2: 'PA', name: 'Panama', country_code3: 'PAN', score: 0 },
  { country_code2: 'PG', name: 'Papua New Guinea', country_code3: 'PNG', score: 0 },
  { country_code2: 'PY', name: 'Paraguay', country_code3: 'PRY', score: 0 },
  { country_code2: 'PE', name: 'Peru', country_code3: 'PER', score: 0 },
  { country_code2: 'PH', name: 'Philippines', country_code3: 'PHL', score: 0 },
  { country_code2: 'PN', name: 'Pitcairn', country_code3: 'PCN', score: 0 },
  { country_code2: 'PL', name: 'Poland', country_code3: 'POL', score: 0 },
  { country_code2: 'PT', name: 'Portugal', country_code3: 'PRT', score: 0 },
  { country_code2: 'PR', name: 'Puerto Rico', country_code3: 'PRI', score: 0 },
  { country_code2: 'QA', name: 'Qatar', country_code3: 'QAT', score: 0 },
  { country_code2: 'RE', name: 'Réunion', country_code3: 'REU', score: 0 },
  { country_code2: 'RO', name: 'Romania', country_code3: 'ROU', score: 0 },
  { country_code2: 'RU', name: 'Russian Federation', country_code3: 'RUS', score: 0 },
  { country_code2: 'RW', name: 'Rwanda', country_code3: 'RWA', score: 0 },
  { country_code2: 'BL', name: 'Saint Barthélemy', country_code3: 'BLM', score: 0 },
  {
    country_code2: 'SH',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    country_code3: 'SHN',
    score: 0
  },
  { country_code2: 'KN', name: 'Saint Kitts and Nevis', country_code3: 'KNA', score: 0 },
  { country_code2: 'LC', name: 'Saint Lucia', country_code3: 'LCA', score: 0 },
  { country_code2: 'MF', name: 'Saint Martin (French part)', country_code3: 'MAF', score: 0 },
  { country_code2: 'PM', name: 'Saint Pierre and Miquelon', country_code3: 'SPM', score: 0 },
  { country_code2: 'VC', name: 'Saint Vincent and the Grenadines', country_code3: 'VCT', score: 0 },
  { country_code2: 'WS', name: 'Samoa', country_code3: 'WSM', score: 0 },
  { country_code2: 'SM', name: 'San Marino', country_code3: 'SMR', score: 0 },
  { country_code2: 'ST', name: 'Sao Tome and Principe', country_code3: 'STP', score: 0 },
  { country_code2: 'SA', name: 'Saudi Arabia', country_code3: 'SAU', score: 0 },
  { country_code2: 'SN', name: 'Senegal', country_code3: 'SEN', score: 0 },
  { country_code2: 'RS', name: 'Serbia', country_code3: 'SRB', score: 0 },
  { country_code2: 'SC', name: 'Seychelles', country_code3: 'SYC', score: 0 },
  { country_code2: 'SL', name: 'Sierra Leone', country_code3: 'SLE', score: 0 },
  { country_code2: 'SG', name: 'Singapore', country_code3: 'SGP', score: 0 },
  { country_code2: 'SX', name: 'Sint Maarten (Dutch part)', country_code3: 'SXM', score: 0 },
  { country_code2: 'SK', name: 'Slovakia', country_code3: 'SVK', score: 0 },
  { country_code2: 'SI', name: 'Slovenia', country_code3: 'SVN', score: 0 },
  { country_code2: 'SB', name: 'Solomon Islands', country_code3: 'SLB', score: 0 },
  { country_code2: 'SO', name: 'Somalia', country_code3: 'SOM', score: 0 },
  { country_code2: 'ZA', name: 'South Africa', country_code3: 'ZAF', score: 0 },
  {
    country_code2: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    country_code3: 'SGS',
    score: 0
  },
  { country_code2: 'SS', name: 'South Sudan', country_code3: 'SSD', score: 0 },
  { country_code2: 'ES', name: 'Spain', country_code3: 'ESP', score: 0 },
  { country_code2: 'LK', name: 'Sri Lanka', country_code3: 'LKA', score: 0 },
  { country_code2: 'SD', name: 'Sudan', country_code3: 'SDN', score: 0 },
  { country_code2: 'SR', name: 'Suriname', country_code3: 'SUR', score: 0 },
  { country_code2: 'SJ', name: 'Svalbard and Jan Mayen', country_code3: 'SJM', score: 0 },
  { country_code2: 'SE', name: 'Sweden', country_code3: 'SWE', score: 0 },
  { country_code2: 'CH', name: 'Switzerland', country_code3: 'CHE', score: 0 },
  { country_code2: 'SY', name: 'Syrian Arab Republic', country_code3: 'SYR', score: 0 },
  { country_code2: 'TW', name: 'Taiwan, Province of China', country_code3: 'TWN', score: 0 },
  { country_code2: 'TJ', name: 'Tajikistan', country_code3: 'TJK', score: 0 },
  { country_code2: 'TZ', name: 'Tanzania, United Republic of', country_code3: 'TZA', score: 0 },
  { country_code2: 'TH', name: 'Thailand', country_code3: 'THA', score: 0 },
  { country_code2: 'TL', name: 'Timor-Leste', country_code3: 'TLS', score: 0 },
  { country_code2: 'TG', name: 'Togo', country_code3: 'TGO', score: 0 },
  { country_code2: 'TK', name: 'Tokelau', country_code3: 'TKL', score: 0 },
  { country_code2: 'TO', name: 'Tonga', country_code3: 'TON', score: 0 },
  { country_code2: 'TT', name: 'Trinidad and Tobago', country_code3: 'TTO', score: 0 },
  { country_code2: 'TN', name: 'Tunisia', country_code3: 'TUN', score: 0 },
  { country_code2: 'TR', name: 'Türkiye', country_code3: 'TUR', score: 0 },
  { country_code2: 'TM', name: 'Turkmenistan', country_code3: 'TKM', score: 0 },
  { country_code2: 'TC', name: 'Turks and Caicos Islands', country_code3: 'TCA', score: 0 },
  { country_code2: 'TV', name: 'Tuvalu', country_code3: 'TUV', score: 0 },
  { country_code2: 'UG', name: 'Uganda', country_code3: 'UGA', score: 0 },
  { country_code2: 'UA', name: 'Ukraine', country_code3: 'UKR', score: 0 },
  { country_code2: 'AE', name: 'United Arab Emirates', country_code3: 'ARE', score: 0 },
  { country_code2: 'GB', name: 'United Kingdom', country_code3: 'GBR', score: 0 },
  {
    country_code2: 'UM',
    name: 'United States Minor Outlying Islands',
    country_code3: 'UMI',
    score: 0
  },
  { country_code2: 'US', name: 'United States of America', country_code3: 'USA', score: 0 },
  { country_code2: 'UY', name: 'Uruguay', country_code3: 'URY', score: 0 },
  { country_code2: 'UZ', name: 'Uzbekistan', country_code3: 'UZB', score: 0 },
  { country_code2: 'VU', name: 'Vanuatu', country_code3: 'VUT', score: 0 },
  {
    country_code2: 'VE',
    name: 'Venezuela, Bolivarian Republic of',
    country_code3: 'VEN',
    score: 0
  },
  { country_code2: 'VN', name: 'Viet Nam', country_code3: 'VNM', score: 0 },
  { country_code2: 'VG', name: 'Virgin Islands, British', country_code3: 'VGB', score: 0 },
  { country_code2: 'VI', name: 'Virgin Islands, U.S.', country_code3: 'VIR', score: 0 },
  { country_code2: 'WF', name: 'Wallis and Futuna', country_code3: 'WLF', score: 0 },
  { country_code2: 'EH', name: 'Western Sahara', country_code3: 'ESH', score: 0 },
  { country_code2: 'YE', name: 'Yemen', country_code3: 'YEM', score: 0 },
  { country_code2: 'ZM', name: 'Zambia', country_code3: 'ZMB', score: 0 },
  { country_code2: 'ZW', name: 'Zimbabwe', country_code3: 'ZWE', score: 0 }
];

exports.seed = async function seed(knex) {
  for (const c of countries) {
    const existing = await knex('countries').where({ country_code2: c.country_code2 }).first();
    if (!existing) {
      await knex('countries').insert(c);
    }
  }
};
